name=input("Enter your name: ")
branch=input("Enter your Branch name: ")
gender=input("Enter your gender: ")
colg=input("Enter college name: ")
age=input("Enter your age: ")
print("Name :",name)
print("Branch :",branch)
print("Gender :",gender)
print("College :",colg)
print("Age :",age)
